package com.salesianostriana.dam.Empelado.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data @NoArgsConstructor
@Embeddable
public class LineaDeVentaPk implements Serializable{
	private static final long serial = 1L;
	private Long ventaId;
	@Column(columnDefinition = "bigint GENERATED BY DEFAULT AS IDENTITY")
	private Long lineDeVentaId;	

}
